class ScaleConverter

  def from_kelvin: (Float degree, String to_scale) -> ::Float

  def from_fahrenheit: (Float degree, String to_scale) -> ::Float

  def from_celsius: (Float degree, String to_scale) -> ::Float

  def convert: (Float degree, String to_scale) -> ::Float
end
